# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  <img src="https://raw.githubusercontent.com/physiopy/physiopy-test-workflows/master/test_banner.png" alt="Thank You Banner" width="200"/>
  
  🎉 Thank you for opening your first issue in this repo! Please check our [contribution guidelines](https://github.com/physiopy/physiopy-community-guidelines) and follow the issue template.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  <img src="https://raw.githubusercontent.com/physiopy/physiopy-test-workflows/master/test_banner.png" alt="Thank You Banner" width="200"/>
  
  🎉 Thanks for opening your first pull request in this repo! Please check our [contribution guidelines](https://github.com/physiopy/physiopy-community-guidelines) and follow the PR template.
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  <img src="https://raw.githubusercontent.com/physiopy/physiopy-test-workflows/master/test_banner.png" alt="Thank You Banner" width="200"/>
  
  🎉 Congrats on merging your first pull request in this repo! We appreciate your contribution to the Physiopy community!
  

